version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map Nginx port 80 to localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"  # Map backend's internal port 5000 to host port 5000
    env_file:
      - ./server/.env  # Load environment variables from .env file
    networks:
      - app-network
# uncomment this the deploying with mongo db
#   mongo:
#     image: mongo:latest  # Use the official MongoDB image
#     container_name: mongo
#     env_file:
#       - ./server/.env
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=test  # Root user for MongoDB (testing)
#       - MONGO_INITDB_ROOT_PASSWORD=test  # Root password for MongoDB (testing)
#     ports:
#       - "27017:27017"  # Expose MongoDB's default port
#     networks:
#       - app-network
#     volumes:
#       - mongo-data:/data/db  # Persist MongoDB data between container restarts

# volumes:
#   mongo-data:  # Volume for MongoDB data persistence

networks:
  app-network:  # Network for inter-service communication
    driver: bridge
